name: charts_flutter
version: 0.12.0
description: Material Design charting library for flutter.
homepage: https://github.com/google/charts

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  # Pointing this to a local path allows for pointing to the latest code
  # in Github for open source development.
  #
  # The pub version of charts_flutter will point to the pub version of charts_common.
  # The latest pub version is commented out and shown below as an example.
  charts_common: ^0.12.0
  # charts_common:
  #   path: ../charts_common/
  # collection: ^1.19.0
  flutter:
    sdk: flutter
  intl: ">=0.15.2 < 0.18.0"
  logging: ^1.2.0
  # meta: ^1.15.0


dev_dependencies:
  mockito: ^5.4.4
  # build_runner: ^2.4.12
  # flutter_test:
  #   sdk: flutter
  # test: ^1.25.8
